version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-sgv
    environment:
      POSTGRES_USER: sgvbank
      POSTGRES_PASSWORD: 00000000
      POSTGRES_DB: sgvbank
    ports:
      - "15432:5432"
    networks:
      - sgvbank_network
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:latest
    container_name: redis-sgv
    ports:
      - "6379:6379"
    networks:
      - sgvbank_network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - sgvbank_network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sgvbank_network
    restart: unless-stopped

networks:
  sgvbank_network:
    driver: bridge

volumes:
  postgres_db: